name: dependencies
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: '>=2.15.1 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  lottie: ^2.0.0
  cached_network_image: ^3.2.2
  shared_preferences: ^2.0.15

  dartz: ^0.10.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
